backend:
  name: git-gateway
  branch: main # ajuste se seu branch for diferente

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "casas"
    label: "Casas"
    files:
      - name: "casas_json"
        label: "Arquivo de casas"
        file: "data/casas.json"
        format: json
        fields:
          - name: "casas"
            label: "Casas"
            widget: "list"
            summary: "{{fields.titulo}} — R$ {{fields.preco}}"
            fields:
              - { name: "id", label: "ID", widget: "string" }
              - { name: "titulo", label: "Título", widget: "string" }
              - { name: "preco", label: "Preço", widget: "number" }
              - { name: "endereco", label: "Endereço", widget: "string" }
              - { name: "descricao", label: "Descrição", widget: "text" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                fields:
                  - { name: "imagem", label: "Imagem", widget: "image" }
